"""empty message

Revision ID: 4dd6ef588897
Revises: 
Create Date: 2019-12-03 15:02:54.420020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd6ef588897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserInfos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Username', sa.String(length=64), nullable=True),
    sa.Column('Email', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=64), nullable=True),
    sa.Column('Sex', sa.String(length=5), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_UserInfos_Email'), 'UserInfos', ['Email'], unique=True)
    op.create_index(op.f('ix_UserInfos_Username'), 'UserInfos', ['Username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_UserInfos_Username'), table_name='UserInfos')
    op.drop_index(op.f('ix_UserInfos_Email'), table_name='UserInfos')
    op.drop_table('UserInfos')
    # ### end Alembic commands ###
